/**
 * Provides configuration details for dashboards, including service types (DBaaS, Linode),
 * related metrics (such as CPU utilization, memory usage, disk I/O), and their properties like
 * expected aggregations, granularity, units, and labels. This configuration is used for validating
 * and interacting with dashboard widgets.
 */
export const widgetDetails = {
  dbaas: {
    clusterName: 'mysql-cluster',
    dashboardName: 'Dbaas Dashboard',
    engine: 'MySQL',
    id: 1,
    metrics: [
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min', 'sum'],
        expectedGranularity: '1 hr',
        name: 'system_disk_OPS_total',
        title: 'Disk I/O',
        unit: 'OPS',
        yLabel: 'system_disk_operations_total',
        filters: [
          { dimension_label: 'device', operator: 'eq', value: 'loop0' },
          { dimension_label: 'direction', operator: 'eq', value: 'write' },
          { dimension_label: 'Linode', operator: 'eq', value: '1' },
        ],
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min'],
        expectedGranularity: '1 hr',
        name: 'system_cpu_utilization_percent',
        title: 'CPU Utilization',
        unit: '%',
        yLabel: 'system_cpu_utilization_ratio',
        filters: [
          { dimension_label: 'cpu', operator: 'eq', value: 'cpu' },
          { dimension_label: 'state', operator: 'eq', value: 'user' },
        ],
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min', 'sum'],
        expectedGranularity: '1 hr',
        name: 'system_memory_usage_by_resource',
        title: 'Memory Usage',
        unit: 'B',
        yLabel: 'system_memory_usage_bytes',
        filters: [{ dimension_label: 'state', operator: 'eq', value: 'used' }],
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min', 'sum'],
        expectedGranularity: '1 hr',
        name: 'system_network_io_by_resource',
        title: 'Network Traffic',
        unit: 'B',
        yLabel: 'system_network_io_bytes_total',
        filters: [
          { dimension_label: 'device', operator: 'eq', value: 'lo' },
          { dimension_label: 'direction', operator: 'eq', value: 'transmit' },
        ],
      },
    ],
    nodeType: 'Secondary',
    region: 'US, Chicago, IL (us-ord)',
    resource: 'Dbaas-resource',
    serviceType: 'dbaas',
  },

  linode: {
    dashboardName: 'Linode Dashboard',
    id: 2,
    metrics: [
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min'],
        expectedGranularity: '1 hr',
        name: 'system_cpu_utilization_percent',
        title: 'CPU Utilization',
        unit: '%',
        yLabel: 'system_cpu_utilization_ratio',
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min', 'sum'],
        expectedGranularity: '1 hr',
        name: 'system_memory_usage_by_resource',
        title: 'Memory Usage',
        unit: 'B',
        yLabel: 'system_memory_usage_bytes',
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min', 'sum'],
        expectedGranularity: '1 hr',
        name: 'system_network_io_by_resource',
        title: 'Network Traffic',
        unit: 'B',
        yLabel: 'system_network_io_bytes_total',
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min', 'sum'],
        expectedGranularity: '1 hr',
        name: 'system_disk_OPS_total',
        title: 'Disk I/O',
        unit: 'OPS',
        yLabel: 'system_disk_operations_total',
      },
    ],
    region: 'US, Chicago, IL (us-ord)',
    resource: 'linode-resource',
    serviceType: 'linode',
  },
  nodebalancer: {
    dashboardName: 'NodeBalancer Dashboard',
    id: 3,
    metrics: [
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['sum'],
        expectedGranularity: '1 hr',
        name: 'system_cpu_utilization_percent',
        title: 'CPU Utilization',
        unit: '%',
        yLabel: 'system_cpu_utilization_ratio',
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['sum'],
        expectedGranularity: '1 hr',
        name: 'system_memory_usage_by_resource',
        title: 'Memory Usage',
        unit: 'B',
        yLabel: 'system_memory_usage_bytes',
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['sum'],
        expectedGranularity: '1 hr',
        name: 'system_network_io_by_resource',
        title: 'Network Traffic',
        unit: 'B',
        yLabel: 'system_network_io_bytes_total',
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['sum'],
        expectedGranularity: '1 hr',
        name: 'system_disk_OPS_total',
        title: 'Disk I/O',
        unit: 'OPS',
        yLabel: 'system_disk_operations_total',
      },
    ],
    region: 'Newark, NJ, USA (us-east)',
    resource: 'NodeBalancer-resource',
    serviceType: 'nodebalancer',
    port: 1,
    protocols: ['TCP', 'UDP'],
  },
  firewall: {
    dashboardName: 'Firewall Dashboard',
    id: 4,
    metrics: [
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['sum'],
        expectedGranularity: '1 hr',
        name: 'system_cpu_utilization_percent',
        title: 'CPU Utilization',
        unit: '%',
        yLabel: 'system_cpu_utilization_ratio',
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['sum'],
        expectedGranularity: '1 hr',
        name: 'system_memory_usage_by_resource',
        title: 'Memory Usage',
        unit: 'B',
        yLabel: 'system_memory_usage_bytes',
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['sum'],
        expectedGranularity: '1 hr',
        name: 'system_network_io_by_resource',
        title: 'Network Traffic',
        unit: 'B',
        yLabel: 'system_network_io_bytes_total',
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['sum'],
        expectedGranularity: '1 hr',
        name: 'system_disk_OPS_total',
        title: 'Disk I/O',
        unit: 'OPS',
        yLabel: 'system_disk_operations_total',
      },
    ],
    firewalls: 'Firewall-0',
    serviceType: 'firewall',
    region: 'Newark',
  },

  firewall_nodebalancer: {
    dashboardName: 'NodeBalancer - Firewall Metrics',
    id: 8,
    serviceType: 'firewall',
    region: 'Newark',
    firewalls: 'Firewall-0',

    mandatoryFilters: [
      { name: 'Region', type: 'single', api: 'list regions' },
      {
        name: 'Cloud Firewall',
        type: 'single',
        api: 'list firewalls',
        comment: 'Show only firewalls attached to nodebalancer entities',
      },
      { name: 'NodeBalancer Region', type: 'single', api: 'list regions' }, // added filter
    ],

    optionalFilters: [
      {
        name: 'NodeBalancer',
        type: 'multi',
        api: 'list devices',
        comment: 'Show only nodebalancers',
      },
    ],

    metrics: [
      {
        name: 'ingress_bytes_accepted',
        title: 'Accepted Bytes',
        unit: 'B',
        chartType: 'line',
        widgetSize: 'large',
        expectedAggregation: 'max',
        expectedAggregationArray: ['sum'],
        expectedGranularity: '1 hr',
        breakdown: ['Cloud Firewall', 'NodeBalancer'],
        yLabel: 'ingress_bytes_accepted',
        filters: [
          // new property added
          {
            dimension_label: 'Protocol',
            type: 'single',
            value: 'list protocols',
          },
          {
            dimension_label: 'IP Version',
            type: 'single',
            value: 'list ip_versions',
          },
        ],
      },
      {
        name: 'ingress_bytes_dropped',
        title: 'Dropped Bytes',
        unit: 'B',
        chartType: 'line',
        widgetSize: 'large',
        expectedAggregation: 'max',
        expectedAggregationArray: ['sum'],
        expectedGranularity: '1 hr',
        breakdown: ['Cloud Firewall', 'NodeBalancer'],
        yLabel: 'ingress_bytes_dropped',
        filters: [
          {
            dimension_label: 'Protocol',
            type: 'single',
            value: 'list protocols',
          },
          {
            dimension_label: 'IP Version',
            type: 'single',
            value: 'list ip_versions',
          },
        ],
      },
      {
        name: 'ingress_packets_accepted',
        title: 'Accepted Packets',
        unit: 'count',
        chartType: 'line',
        widgetSize: 'large',
        expectedAggregation: 'max',
        expectedAggregationArray: ['sum'],
        expectedGranularity: '1 hr',
        breakdown: ['Cloud Firewall', 'NodeBalancer'],
        yLabel: 'ingress_packets_accepted',
        filters: [
          {
            dimension_label: 'Protocol',
            type: 'single',
            value: 'list protocols',
          },
          {
            dimension_label: 'Protocol',
            type: 'single',
            value: 'list protocols',
          },
        ],
      },
      {
        name: 'ingress_packets_dropped',
        title: 'Dropped Packets',
        unit: 'count',
        chartType: 'line',
        widgetSize: 'large',
        expectedAggregation: 'max',
        expectedAggregationArray: ['sum'],
        expectedGranularity: '1 hr',
        breakdown: ['Cloud Firewall', 'NodeBalancer'],
        yLabel: 'ingress_packets_dropped',
        filters: [
          // new property added
          {
            dimension_label: 'Protocol',
            type: 'single',
            value: 'list protocols',
          },
          {
            dimension_label: 'IP Version',
            type: 'single',
            value: 'list ip_versions',
          },
          {
            dimension_label: 'nodebalancer_id',
            type: 'single',
            value: 'list ip_versions',
          },
        ],
      },
    ],

    dimensions: [
      { key: 'region_id', exposed: false },
      { key: 'entity_id', displayName: 'Cloud Firewall', exposed: true },
      { key: 'nodebalancer_id', displayName: 'NodeBalancer', exposed: true },
      {
        key: 'ip_version',
        displayName: 'IP Version',
        values: ['v4', 'v6'],
        exposed: true,
      },
      {
        key: 'protocol',
        displayName: 'Protocol',
        values: ['tcp', 'udp'],
        exposed: true,
      },
    ],
  },

  objectstorage: {
    dashboardName: 'Object Storage Dashboard',
    id: 6,
    metrics: [
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min'],
        expectedGranularity: '1 hr',
        name: 'obj_bucket_size',
        title: 'Total Bucket Size',
        unit: 'B',
        yLabel: 'obj_bucket_size',
        filters: [
          { dimension_label: 'endpoint', operator: 'eq', value: null },
          { dimension_label: 'request_type', operator: 'eq', value: null },
        ],
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min'],
        expectedGranularity: '1 hr',
        name: 'obj_requests_num',
        title: 'All Requests',
        unit: 'Count',
        yLabel: 'obj_requests_num',
        filters: [
          { dimension_label: 'endpoint', operator: 'eq', value: null },
          { dimension_label: 'request_type', operator: 'eq', value: null },
        ],
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min'],
        expectedGranularity: '1 hr',
        name: 'obj_responses_num',
        title: 'All Responses',
        unit: 'Count',
        yLabel: 'obj_responses_num',
        filters: [
          { dimension_label: 'endpoint', operator: 'eq', value: null },
          { dimension_label: 'response_type', operator: 'eq', value: null },
        ],
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min'],
        expectedGranularity: '1 hr',
        name: 'obj_bytes_downloaded',
        title: 'Bytes Downloaded',
        unit: 'B',
        yLabel: 'obj_bytes_downloaded',
        filters: [
          { dimension_label: 'endpoint', operator: 'eq', value: null },
          { dimension_label: 'response_type', operator: 'eq', value: null },
        ],
      },
    ],
    region: 'Chicago',
    serviceType: 'objectstorage',
  },
  blockstorage: {
    dashboardName: 'Block Storage Dashboard',
    id: 7,
    metrics: [
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min'],
        expectedGranularity: '1 hr',
        name: 'volume_read_ops',
        title: 'Volume Read Operations',
        unit: 'Count',
        yLabel: 'volume_read_ops',
        filters: [
          { dimension_label: 'linode_id', operator: 'eq', value: null },
          { dimension_label: 'entity_id', operator: 'eq', value: null },
          { dimension_label: 'response_type', operator: 'eq', value: null },
        ],
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min'],
        expectedGranularity: '1 hr',
        name: 'volume_write_ops',
        title: 'Volume Write Operations',
        unit: 'Count',
        yLabel: 'volume_write_ops',
        filters: [
          { dimension_label: 'linode_id', operator: 'eq', value: null },
          { dimension_label: 'entity_id', operator: 'eq', value: null },
          { dimension_label: 'response_type', operator: 'eq', value: null },
        ],
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min'],
        expectedGranularity: '1 hr',
        name: 'volume_read_bytes',
        title: 'Volume Read Bytes',
        unit: 'B',
        yLabel: 'volume_read_bytes',
        filters: [
          { dimension_label: 'linode_id', operator: 'eq', value: null },
          { dimension_label: 'entity_id', operator: 'eq', value: null },
          { dimension_label: 'response_type', operator: 'eq', value: null },
        ],
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min'],
        expectedGranularity: '1 hr',
        name: 'volume_write_bytes',
        title: 'Volume Write Bytes',
        unit: 'B',
        yLabel: 'volume_write_bytes',
        filters: [
          { dimension_label: 'linode_id', operator: 'eq', value: null },
          { dimension_label: 'entity_id', operator: 'eq', value: null },
          { dimension_label: 'response_type', operator: 'eq', value: null },
        ],
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min'],
        expectedGranularity: '1 hr',
        name: 'volume_read_latency',
        title: 'Volume Read Latency',
        unit: 'ms',
        yLabel: 'volume_read_latency',
        filters: [
          { dimension_label: 'linode_id', operator: 'eq', value: null },
          { dimension_label: 'percentile', operator: 'eq', value: null },
        ],
      },
      {
        expectedAggregation: 'max',
        expectedAggregationArray: ['avg', 'max', 'min'],
        expectedGranularity: '1 hr',
        name: 'volume_write_latency',
        title: 'Volume Write Latency',
        unit: 'ms',
        yLabel: 'volume_write_latency',
        filters: [
          { dimension_label: 'percentile', operator: 'eq', value: null },
        ],
      },
    ],
    region: 'Chicago',
    serviceType: 'blockstorage',
  },
};