import { API_ROOT } from 'src/constants';

import Request, { setData, setMethod, setURL } from '..';
import { enableTwoFactorSchema } from './twofactor.schema';

type Secret = Linode.Secret;

/**
 * getTFAToken
 *
 * Generate a token for enabling two-factor authentication.
 * Used for authorizing 3rd party apps such as Authy and
 * Google Authenticator. This token can be input manually
 * into one of these 3rd party apps, or can be used to
 * generate a QR code for users to scan.
 *
 */
export const getTFAToken = () =>
  Request<Secret>(setMethod('POST'), setURL(`${API_ROOT}/profile/tfa-enable`));

/**
 * disableTwoFactor
 *
 * Disable two-factor authentication for the current user.
 * All tokens generated by authorized apps will no longer
 * be valid.
 *
 */
export const disableTwoFactor = () =>
  Request<{}>(setMethod('POST'), setURL(`${API_ROOT}/profile/tfa-disable`));

/**
 * confirmTwoFactor
 *
 * Use a two-factor code generated by a third-party app
 * to confirm that Two Factor Authentication has been
 * configured correctly. If this call succeeds, TFA will
 * be enabled on future logins for your account.
 *
 * @param code { string } Code generated by Authy/Google Authenticator/etc.
 *   after the QR code has been scanned.
 *
 * @returns a scratch code: a one-use code that can be used in place of your Two Factor code,
 * in case you are unable to generate one. Keep this in a safe place to avoid
 * being locked out of your Account.
 */
export const confirmTwoFactor = (tfa_code: string) =>
  Request<{ scratch: string }>(
    setMethod('POST'),
    setURL(`${API_ROOT}/profile/tfa-enable-confirm`),
    setData({ tfa_code }, enableTwoFactorSchema)
  ).then(response => response.data);
