FROM cypress/base:12.8.1
# Run commands as "node" user. We don't want to run these commands as root
#
# See https://github.com/nodejs/docker-node/blob/d094c98a48659ff9f8d59db8dafb7020e181446a/docs/BestPractices.md
# and https://github.com/nodejs/docker-node/issues/1
WORKDIR /home/node/app
RUN chown -R node:node /home/node/app
USER node

# Copy the root level package.json and run yarn if anything changes
COPY --chown=node:node package.json yarn.lock run_cypress_docker.sh scripts ./

# Copy the rest of the files that don't require installation
COPY --chown=node:node packages/api-v4  ./packages/api-v4/
COPY --chown=node:node packages/manager ./packages/manager

# Runs "yarn install" for all child packages
RUN yarn install:all && yarn run cypress verify && yarn build:sdk

ENTRYPOINT ["sh","run_cypress_docker.sh"]

