version: '3.1'
services: 
  selenium-standalone:
    image: selenium/standalone-chrome:3.13.0-argon
    volumes:
      - /dev/shm:/dev/shm #Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    environment:
      - SCREEN_HEIGHT=1080
      - SCREEN_WIDTH=1600
  manager-local:
    environment:
      - HTTPS=true
      - REACT_APP_APP_ROOT=https://manager-local:3000
      - REACT_APP_LOGIN_ROOT=${REACT_APP_LOGIN_ROOT}
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
      - REACT_APP_API_ROOT=${REACT_APP_API_ROOT}
      - REACT_APP_TEST_ENVIRONMENT=true
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/src/scripts/start_manager.sh"]
    depends_on:
      - selenium-standalone
  manager-e2e:
    environment:
      - DOCKER=true
      - REACT_APP_API_ROOT=${REACT_APP_API_ROOT}
      - MANAGER_USER=${MANAGER_USER}
      - MANAGER_PASS=${MANAGER_PASS}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./e2e/test-results:/src/e2e/test-results
    entrypoint: ["./scripts/wait-for-it.sh", "-t", "250", "-s", "manager-local:3000", "--", "yarn","e2e", "--log"]
    depends_on:
      - manager-local

