version: '3.1'
services: 
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  manager-storybook:
    container_name: manager_storybook
    ports:
      - "6006:6006"
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: yarn storybook
    depends_on:
      - chrome
  manager-local:
    container_name: manager_local
    ports:
      - "3000:3000"
    environment:
      - HTTPS=true
      - REACT_APP_APP_ROOT=https://manager-local:3000
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: yarn start
  manager-e2e:
    container_name: manager_e2e
    environment:
      - DOCKER=true
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./scripts/wait-for-it.sh", "-t", "250", "-s", "manager-local:3000", "--", "yarn","e2e"]
    depends_on:
      - manager-storybook
      - manager-local