version: '3.1'
services: 
  selenium-standalone:
    image: selenium/standalone-chrome:3.4.0-francium
    volumes:
      - /dev/shm:/dev/shm #Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    networks:
      - backend
  manager-local:
    container_name: manager_local
    environment:
      - HTTPS=true
      - REACT_APP_APP_ROOT=https://manager-local:3000
      - REACT_APP_LOGIN_ROOT=${REACT_APP_LOGIN_ROOT}
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
      - REACT_APP_API_ROOT=${REACT_APP_API_ROOT}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src/src
    entrypoint: ["/src/scripts/start_manager.sh"]
  manager-e2e:
    container_name: manager_e2e
    environment:
      - DOCKER=true
      - REACT_APP_API_ROOT=${REACT_APP_API_ROOT}
      - MANAGER_USER=${MANAGER_USER}
      - MANAGER_PASS=${MANAGER_PASS}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src/src
      - ./e2e:/src/e2e
    entrypoint: ["./scripts/wait-for-it.sh", "-t", "250", "-s", "manager-local:3000", "--", "yarn","e2e", "--log"]
    depends_on:
      - manager-local
