version: '3.1'
services:
  manager-storybook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /src/src/components:/src/src/components
    entrypoint: ["/src/src/scripts/storybook_static.sh"]
  manager-storyshots:
    environment:
      - UPDATE=${UPDATE}
    build:
        context: .
        dockerfile: Dockerfile-storyshots
    volumes:
      - /src/src/components:/src/src/components
    depends_on:
      - manager-storybook
    entrypoint: ["/src/scripts/storyshots_entrypoint.sh"]
