version: '3.1'
services:
  manager-storybook:
    container_name: manager_storybook
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src/src
    entrypoint: ["./scripts/storybook_static.sh"]
    networks:
      - backend
  manager-storyshots:
    container_name: manager_storyshots
    environment:
      - UPDATE=${UPDATE}
    build:
        context: .
        dockerfile: Dockerfile-storyshots
    volumes:
      - ./src:/src/src
    depends_on:
      - manager-storybook
    entrypoint: ["./scripts/storyshots_entrypoint.sh"]
    networks:
        - backend
networks:
  backend:
