version: '3.1'
services: 
  selenium-hub:
    image: selenium/hub:3.11.0-bismuth
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.11.0-bismuth
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm #Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  manager-storybook:
    container_name: manager_storybook
    ports:
      - "6006:6006"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src/src
    entrypoint: yarn storybook
    depends_on:
      - chrome
  storybook-test:
    container_name: storybook_test
    environment:
      - DOCKER=true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src/src
      - ./e2e:/src/e2e
      - ./storybook-test-results:/src/storybook-test-results
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
    entrypoint: ["./scripts/storybook_entrypoint.sh"]
    depends_on:
      - manager-storybook
