version: '3.1'
services:
  selenium:
    image: selenium/hub:3.13.0-argon
  chrome:
    image: selenium/node-chrome:3.13.0-argon
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium
      - HUB_PORT_4444_TCP_PORT=4444
      - SCREEN_HEIGHT=1080
      - SCREEN_WIDTH=1600
    depends_on:
      - selenium
  imposter:
    build:
      context: .
      dockerfile: Dockerfile-mountebank
    entrypoint: ['mb', '--configfile', 'data/visual-regression.json']
    depends_on:
      - chrome
  manager-local:
    environment:
      - REACT_APP_APP_ROOT=https://manager-local:3000
      - REACT_APP_LOGIN_ROOT=https://login.linode.com
      - REACT_APP_CLIENT_ID=8e117503496dd81bdc47
      - REACT_APP_API_ROOT=http://imposter:8088/v4
      - REACT_APP_ALGOLIA_APPLICATION_ID=KGUN8FAIPF
      - REACT_APP_ALGOLIA_SEARCH_KEY=d4847002cd30392fe0fbd00a1da933ed
      - REACT_APP_TEST_ENVIRONMENT=true
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['./scripts/start_manager.sh']
    depends_on:
      - imposter
  manager-e2e:
    environment:
      - REACT_APP_APP_ROOT=https://manager-local:3000
      - REACT_APP_API_ROOT=http://imposter:8088/v4
      - DOCKER=true
      - MANAGER_USER=prod-test-010
      - MANAGER_PASS=${password-in-1pass}
      - MANAGER_USER_2=prod-test-012
      - MANAGER_PASS_2=${password-in-1pass}
      - MANAGER_OAUTH=${token-in-1pass}
      - MANAGER_OAUTH_2=${token-in-1pass}
    volumes:
      - ./e2e/test-results:/src/e2e/test-results
      - ./e2e/html-results:/src/e2e/html-results
      - ./e2e/visual-regression/baseline:/src/e2e/visual-regression/baseline
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['./scripts/visual-regression-entrypoint.sh']
