import type { GrantLevel, LinodeAdmin } from '@linode/api-v4';

/** Map the existing Grant model to the new IAM RBAC model. */
export const linodeGrantsToPermissions = (
  grantLevel?: GrantLevel
): Record<LinodeAdmin, boolean> => {
  return {
    cancel_linode_backups: grantLevel === 'read_write',
    delete_linode: grantLevel === 'read_write',
    delete_linode_config_profile: grantLevel === 'read_write',
    delete_linode_config_profile_interface: grantLevel === 'read_write',
    delete_linode_disk: grantLevel === 'read_write',
    apply_linode_firewalls: grantLevel === 'read_write',
    boot_linode: grantLevel === 'read_write',
    clone_linode: grantLevel === 'read_write',
    clone_linode_disk: grantLevel === 'read_write',
    create_linode_backup_snapshot: grantLevel === 'read_write',
    create_linode_config_profile: grantLevel === 'read_write',
    create_linode_config_profile_interface: grantLevel === 'read_write',
    create_linode_disk: grantLevel === 'read_write',
    enable_linode_backups: grantLevel === 'read_write',
    generate_linode_lish_token: grantLevel === 'read_write',
    generate_linode_lish_token_remote: grantLevel === 'read_write',
    migrate_linode: grantLevel === 'read_write',
    password_reset_linode: grantLevel === 'read_write',
    reboot_linode: grantLevel === 'read_write',
    rebuild_linode: grantLevel === 'read_write',
    reorder_linode_config_profile_interfaces: grantLevel === 'read_write',
    rescue_linode: grantLevel === 'read_write',
    reset_linode_disk_root_password: grantLevel === 'read_write',
    resize_linode: grantLevel === 'read_write',
    resize_linode_disk: grantLevel === 'read_write',
    restore_linode_backup: grantLevel === 'read_write',
    shutdown_linode: grantLevel === 'read_write',
    update_linode: grantLevel === 'read_write',
    update_linode_config_profile: grantLevel === 'read_write',
    update_linode_config_profile_interface: grantLevel === 'read_write',
    update_linode_disk: grantLevel === 'read_write',
    update_linode_firewalls: grantLevel === 'read_write',
    upgrade_linode: grantLevel === 'read_write',
    list_linode_firewalls: grantLevel !== null,
    list_linode_nodebalancers: grantLevel !== null,
    list_linode_volumes: grantLevel !== null,
    view_linode: grantLevel !== null,
    view_linode_backup: grantLevel !== null,
    view_linode_config_profile: grantLevel !== null,
    view_linode_config_profile_interface: grantLevel !== null,
    view_linode_disk: grantLevel !== null,
    view_linode_monthly_network_transfer_stats: grantLevel !== null,
    view_linode_monthly_stats: grantLevel !== null,
    view_linode_network_transfer: grantLevel !== null,
    view_linode_stats: grantLevel !== null,
  };
};
