import { API_ROOT } from 'src/constants';

import Request, { setData, setMethod, setURL } from '..';

export interface Secret {
  secret: string;
  expiry: Date;
}

/**
 * getTFAToken
 *
 * Generate a token for enabling two-factor authentication.
 * Used for authorizing 3rd party apps such as Authy and 
 * Google Authenticator.
 * 
 * 
 */
export const getTFAToken = () =>
  Request<Secret>(
    setMethod('POST'),
    setURL(`${API_ROOT}/profile/tfa-enable`)
  )

/**
 * disableTwoFactor
 *
 * Disable two-factor authentication for the current user.
 * All tokens generated by authorized apps will no longer
 * be valid.
 * 
 */
export const disableTwoFactor = () =>
  Request<{}>(
    setMethod('POST'),
    setURL(`${API_ROOT}/profile/tfa-disable`)
  )

/**
 * confirmTwoFactor
 *
 * Use a two-factor code generated by a third-party app
 * to confirm that Two Factor Authentication has been
 * configured correctly. If this call succeeds, TFA will
 * be enabled on future logins for your account.
 * 
 */
export const confirmTwoFactor = (code: string) =>
  Request<{}>(
    setMethod('POST'),
    setURL(`${API_ROOT}/profile/tfa-enable-confirm`),
    setData({ tfa_code: code })
  )