import { compose } from 'ramda';
import * as React from 'react';

import {
    StyleRulesCallback,
    Theme,
    WithStyles,
    withStyles,
  } from '@material-ui/core/styles';  
import Typography from '@material-ui/core/Typography';

import ActionsPanel from 'src/components/ActionsPanel';
import Button from 'src/components/Button';
import RenderGuard from 'src/components/RenderGuard';
import TextField from 'src/components/TextField';

type ClassNames = 'root';

const styles: StyleRulesCallback<ClassNames> = (theme: Theme) => ({
  root: {},
});

interface Props {
  token: string;
  submitting: boolean;
  error?: string;
  handleChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  onCancel: () => void;
  onSubmit: () => void;
}

type CombinedProps = Props & WithStyles<ClassNames>;

const ConfirmToken: React.StatelessComponent<CombinedProps> = (props) => {
  const { token, error, handleChange, onSubmit, submitting, onCancel } = props;
  
  return (
    <React.Fragment>
      <Typography
        variant="body1"
        data-qa-copy
      >
        Please enter the token generated by your TFA app:
      </Typography>
      <TextField
        value={token}
        errorText={error}
        label="Token"
        onChange={handleChange}
        data-qa-confirm-token
      />
      <ActionsPanel>
        <Button
          type="primary"
          onClick={onSubmit}
          loading={submitting}
          data-qa-submit
        >
          Confirm Token
        </Button>
        <Button
          type="cancel"
          onClick={onCancel}
          data-qa-cancel
        >
          Cancel
        </Button>
      </ActionsPanel>
    </React.Fragment>
  );
}

const styled = withStyles(styles, { withTheme: true });

export default compose<any, any, any>(
  styled,
  RenderGuard
  )(ConfirmToken);
