export const assertLog = {
  displayed: 'should be displayed',
  enabled: 'should be enabled',
  notDisplayed: 'should not be displayed',
  notEnabled: 'should not be enabled',
  incorrectText: 'incorrect text found',
  incorrectRegExVal: 'incorrect value found for regex with',
  incorrectNum: 'incorrect number of items',
  incorrectVal: 'incorrect value found',
  incorrectAttr: 'incorrect attribute found for',
  incorrectOrder: 'not ordered correctly',
  incorrectTag: 'incorrect or missing tag for',
  incorrectTagName: 'incorrect tag name for',
  shouldNotBeNull: 'value should not be null',
  shouldExist: 'element should exist in DOM',
  shouldContain: 'text should have contained',
};
