import React, { Component, PropTypes } from 'react';
import QRious from 'qrious';

import { ConfirmModalBody } from 'linode-components/modals';

import { showModal, hideModal } from '~/actions/modal';
import { confirmTFA } from '~/api/profile';
import { ModalFormGroup, FormGroupError, Input } from 'linode-components/forms';
import { dispatchOrStoreErrors, FormSummary } from '~/components/forms';


export class TwoFactorModal extends Component {
  constructor(props) {
    super(props);

    this.state = {
      tfaCode: '',
      errors: {},
    };
  }

  onSubmit = () => {
    const { dispatch, toggleTwoFactor } = this.props;
    const { tfaCode } = this.state;

    return dispatch(dispatchOrStoreErrors.call(this, [
      () => confirmTFA(tfaCode),
      ({ scratch }) => this.twoFactorScratchModal(scratch),
    ]));
  }

  twoFactorScratchModal(scratch) {
    return (dispatch) => dispatch(showModal('Two-Factor Authentication Enabled',
      <ConfirmModalBody
        buttonText="Ok"
        onOk={() => dispatch(hideModal())}
        onCancel={() => dispatch(hideModal())}
      >
        <p>
          Two-Factor authentication has been enabled. And a new emergency one-time use scratch code
          has been generated. Store this somewhere safe.
        </p>
        <div className="alert alert-warning">{scratch}</div>
      </ConfirmModalBody>
    ));
  }

  onChange = ({ target: { name, value } }) => this.setState({ [name]: value })

  render() {
    const { dispatch, secret, username } = this.props;
    const { tfaCode, errors } = this.state;
    const QRcode = new QRious({
      value: `otpauth://totp/LinodeManager%3A${username}?secret=${secret}`,
      level: 'H',
      size: 250,
    });

    return (
      <div className="TwoFactorModal">
        <ConfirmModalBody
          buttonText="Enable"
          buttonDisabledText="Enabling"
          onOk={this.onSubmit}
          onCancel={() => dispatch(hideModal())}
        >
          <div>
            <p>Scan this QR code to add your Linode account to your TFA app.</p>
            <div className="text-sm-center">
              <img src={QRcode.toDataURL()} alt={secret} />
            </div>
            <p>Please enter the token generated by your TFA app.</p>
            <ModalFormGroup errors={errors} id="tfaCode" name="tfa_code" label="Token">
              <Input
                id="tfaCode"
                name="tfaCode"
                value={tfaCode}
                placeholder="901928"
                onChange={this.onChange}
              />
              <FormGroupError errors={errors} name="tfa_code" inline={false} />
            </ModalFormGroup>
            <small>
              If your TFA app does not have a QR scanner, you can use this secret key.
            </small>
            <div className="alert alert-warning">{secret}</div>
          </div>
        </ConfirmModalBody>
        <FormSummary errors={errors} />
      </div>
    );
  }
}

TwoFactorModal.propTypes = {
  dispatch: PropTypes.func.isRequired,
  toggleTwoFactor: PropTypes.func,
  secret: PropTypes.string,
  profile: PropTypes.object,
};
