import { Image } from 'linode-js-sdk/lib/images';

export const images: Image[] = [
  {
    created_by: 'linode',
    deprecated: true,
    id: 'linode/slackware13',
    vendor: 'Slackware',
    size: 600,
    type: 'manual',
    created: '2011-06-05T19:11:59',
    is_public: true,
    label: 'Slackware 13.37',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/slackware14',
    vendor: 'Slackware',
    size: 1000,
    type: 'manual',
    created: '2013-11-25T16:11:02',
    is_public: true,
    label: 'Slackware 14.1',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: true,
    id: 'linode/ubuntu12',
    vendor: 'Ubuntu',
    size: 550,
    type: 'manual',
    created: '2014-04-28T18:16:59',
    is_public: true,
    label: 'Ubuntu 12.04 LTS',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: true,
    id: 'linode/centos6',
    vendor: 'CentOS',
    size: 675,
    type: 'manual',
    created: '2014-04-28T19:19:34',
    is_public: true,
    label: 'CentOS 6.5',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/centos7',
    vendor: 'CentOS',
    size: 750,
    type: 'manual',
    created: '2014-07-08T14:07:21',
    is_public: true,
    label: 'CentOS 7',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/debian7',
    vendor: 'Debian',
    size: 600,
    type: 'manual',
    created: '2014-09-24T17:59:32',
    is_public: true,
    label: 'Debian 7',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/opensuse13.2',
    vendor: 'openSUSE',
    size: 700,
    type: 'manual',
    created: '2014-12-17T22:55:42',
    is_public: true,
    label: 'openSUSE 13.2',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/debian8',
    vendor: 'Debian',
    size: 900,
    type: 'manual',
    created: '2015-04-27T20:26:41',
    is_public: true,
    label: 'Debian 8.1',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/Ubuntu16.04LTS',
    vendor: null,
    size: 800,
    type: 'manual',
    created: '2016-04-22T18:11:29',
    is_public: true,
    label: 'Ubuntu 16.04 LTS',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: true,
    id: 'linode/Fedora23',
    vendor: 'Fedora',
    size: 1700,
    type: 'manual',
    created: '2016-05-26T17:36:32',
    is_public: true,
    label: 'Fedora 23',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/Arch2016.09.03',
    vendor: 'Arch',
    size: 1639,
    type: 'manual',
    created: '2016-06-13T20:31:34',
    is_public: true,
    label: 'Arch 2016.09.03',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: true,
    id: 'linode/Fedora24',
    vendor: 'Fedora',
    size: 1024,
    type: 'manual',
    created: '2016-06-22T19:03:38',
    is_public: true,
    label: 'Fedora 24',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: true,
    id: 'linode/openSUSELeap42.1',
    vendor: 'openSUSE',
    size: 1700,
    type: 'manual',
    created: '2016-06-27T17:01:16',
    is_public: true,
    label: 'openSUSE Leap 42.1',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/Slackware14.2',
    vendor: 'Slackware',
    size: 1700,
    type: 'manual',
    created: '2016-10-13T13:14:34',
    is_public: true,
    label: 'Slackware 14.2',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/Ubuntu16.10',
    vendor: 'Ubuntu',
    size: 1300,
    type: 'manual',
    created: '2016-10-13T21:22:25',
    is_public: true,
    label: 'Ubuntu 16.10',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/Gentoo2016-10-13',
    vendor: 'Gentoo',
    size: 2000,
    type: 'manual',
    created: '2016-10-25T17:31:25',
    is_public: true,
    label: 'Gentoo 2016-10-13',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/openSUSELeap42.2',
    vendor: 'openSUSE',
    size: 1700,
    type: 'manual',
    created: '2016-11-17T19:52:54',
    is_public: true,
    label: 'openSUSE Leap 42.2',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/Fedora25',
    vendor: 'Fedora',
    size: 1500,
    type: 'manual',
    created: '2016-11-28T19:53:47',
    is_public: true,
    label: 'Fedora 25',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/debian9',
    vendor: 'Debian',
    size: 1100,
    type: 'manual',
    created: '2017-06-16T20:02:29',
    is_public: true,
    label: 'Debian 9',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/debian8.7',
    vendor: 'Debian',
    size: 1100,
    type: 'manual',
    created: '2017-08-15T22:28:13',
    is_public: true,
    label: 'Debian 8.7',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/containerlinux',
    vendor: 'CoreOS',
    size: 3000,
    type: 'manual',
    created: '2017-08-15T22:28:13',
    is_public: true,
    label: 'Container Linux',
    description: null,
    expiry: null
  }
];

export const privateImages: Image[] = [
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/debian8.7',
    vendor: 'Debian',
    size: 1100,
    type: 'manual',
    created: '2017-08-15T22:28:13',
    is_public: false,
    label: 'Debian 8.7',
    description: null,
    expiry: null
  },
  {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/containerlinux',
    vendor: 'CoreOS',
    size: 3000,
    type: 'manual',
    created: '2017-08-15T22:28:13',
    is_public: false,
    label: 'Container Linux',
    description: null,
    expiry: null
  }
];

export const normalizedImages = {
  'linode/debian8.7': {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/debian8.7',
    vendor: 'Debian',
    size: 1100,
    type: 'manual',
    created: '2017-08-15T22:28:13',
    is_public: true,
    label: 'Debian 8.7',
    description: null,
    expiry: null
  },
  'linode/containerlinux': {
    created_by: 'linode',
    deprecated: false,
    id: 'linode/containerlinux',
    vendor: 'CoreOS',
    size: 3000,
    type: 'manual',
    created: '2017-08-15T22:28:13',
    is_public: true,
    label: 'Container Linux',
    description: null,
    expiry: null
  }
};
