import { Region } from '@linode/api-v4/lib/regions';

const resolvers = {
  ipv4: '8.8.8.8',
  ipv6: '2600:3c03::5',
};

export const regions: Region[] = [
  {
    capabilities: ['Linodes', 'NodeBalancers', 'Block Storage'],
    country: 'IN',
    id: 'ap-west',
    label: 'Mumbai, IN',
    resolvers,
    status: 'ok',
  },
  {
    capabilities: ['Linodes', 'NodeBalancers', 'Block Storage'],
    country: 'AU',
    id: 'ap-southeast',
    label: 'Sydney, AU',
    resolvers,
    status: 'ok',
  },
  {
    capabilities: ['Linodes', 'NodeBalancers', 'Block Storage'],
    country: 'CA',
    id: 'ca-central',
    label: 'Toronto, CA',
    resolvers,
    status: 'ok',
  },
  {
    capabilities: ['Linodes', 'NodeBalancers', 'Block Storage'],
    country: 'US',
    id: 'us-central',
    label: 'Dallas, TX',
    resolvers,
    status: 'ok',
  },
  {
    capabilities: ['Linodes', 'NodeBalancers', 'Block Storage'],
    country: 'US',
    id: 'us-west',
    label: 'Fremont, CA',
    resolvers,
    status: 'ok',
  },
  {
    capabilities: ['Linodes', 'NodeBalancers'],
    country: 'US',
    id: 'us-southeast',
    label: 'Atlanta, GA',
    resolvers,
    status: 'ok',
  },
  {
    capabilities: [
      'Linodes',
      'NodeBalancers',
      'Block Storage',
      'Object Storage',
    ],
    country: 'US',
    id: 'us-east',
    label: 'Newark, NJ',
    resolvers,
    status: 'ok',
  },
  {
    capabilities: ['Linodes', 'NodeBalancers', 'Block Storage'],
    country: 'UK',
    id: 'eu-west',
    label: 'London, UK',
    resolvers,
    status: 'ok',
  },
  {
    capabilities: ['Linodes', 'NodeBalancers', 'Block Storage'],
    country: 'SG',
    id: 'ap-south',
    label: 'Singapore, SG',
    resolvers,
    status: 'ok',
  },
  {
    capabilities: ['Linodes', 'NodeBalancers', 'Block Storage'],
    country: 'DE',
    id: 'eu-central',
    label: 'Frankfurt, DE',
    resolvers,
    status: 'ok',
  },
  {
    capabilities: ['Linodes', 'NodeBalancers', 'Block Storage'],
    country: 'JP',
    id: 'ap-northeast',
    label: 'Tokyo, JP',
    resolvers,
    status: 'ok',
  },
];
