import { StackScript } from '@linode/api-v4/lib/stackscripts';

export const stackScripts: StackScript[] = [
  {
    created: '2018-07-10T15:30:56',
    deployments_active: 0,
    deployments_total: 0,
    description: 'this\n\n\n\nis\n\n\n\n\nmy public jawn',
    id: 326426,
    images: ['linode/containerlinux', 'linode/debian8', 'linode/fedora27'],
    is_public: true,
    label: 'is_public',
    logo_url: '',
    mine: true,
    ordinal: 1,
    rev_note: 'my note!',
    script: '#!/bin/bash',
    updated: '2018-07-10T15:30:56',
    user_defined_fields: [],
    user_gravatar_id: '8c73c32a9e8f9868ce536b132bb62613',
    username: 'mmckenna',
  },
  {
    created: '2018-07-10T15:30:56',
    deployments_active: 0,
    deployments_total: 0,
    description: 'this\n\n\n\nis\n\n\n\n\nmy public jawn',
    id: 326432426,
    images: [
      'linode/containerlinux',
      'linode/debian8',
      'linode/fedora27',
      'linode/centos7',
      'linode/centos6',
      'linode/coreos',
    ],
    is_public: true,
    label: 'is_public',
    logo_url: '',
    mine: true,
    ordinal: 1,
    rev_note: 'my note!',
    script: '#!/bin/bash',
    updated: '2018-07-10T15:30:56',
    user_defined_fields: [],
    user_gravatar_id: '8c73c32a9e8f9868ce536b132bb62613',
    username: 'mmckenna',
  },
];
