import Factory from 'src/factories/factoryProxy';

import type { IamAccountPermissions } from '@linode/api-v4';

export const accountPermissionsFactory = Factory.Sync.makeFactory<IamAccountPermissions>(
  {
    account_access: [
      {
        resource_type: 'account',
        roles: [
          {
            description: 'Access to view all resources in the account',
            name: 'account_viewer',
            permissions: [
              'view_account',
              'view_account_settings',
              'view_network_usage',
              'list_events',
              'list_service_transfers',
              'list_notifications',
              'list_account_logins',
              'list_oauth_clients',
              'list_available_services',
              'list_account_agreements',
              'list_child_accounts',
              'view_user',
              'list_users',
              'view_linode',
              'view_linode_stats',
              'view_linode_monthly_stats',
              'view_linode_network_transfer',
              'view_linode_monthly_network_transfer_stats',
              'list_linode_types',
              'list_linode_volumes',
              'list_linode_backups',
              'list_linode_config_profiles',
              'list_linode_disks',
              'list_linode_firewalls',
              'view_linode_networking_info',
              'list_linode_nodebalancers',
              'list_linode_kernels',
              'view_linode_type',
              'view_linode_backup',
              'view_linode_config_profile',
              'list_linode_config_profile_interfaces',
              'view_linode_config_profile_interface',
              'view_linode_disk',
              'view_linode_ip_address',
              'view_linode_kernel',
              'view_image',
              'view_vpc',
              'list_vpc_ip_addresses',
              'list_vpc_subnets',
              'view_vpc_subnet',
              'view_volume',
              'view_nodebalancer',
              'list_nodebalancer_firewalls',
              'view_nodebalancer_statistics',
              'list_nodebalancer_configs',
              'view_nodebalancer_config',
              'list_nodebalancer_config_nodes',
              'view_nodebalancer_config_node',
            ],
          },
          {
            description:
              'Access to perform any supported action on all resources in the account',
            name: 'account_admin',
            permissions: [
              'view_account',
              'view_account_settings',
              'view_network_usage',
              'list_events',
              'list_service_transfers',
              'list_notifications',
              'list_account_logins',
              'list_oauth_clients',
              'list_available_services',
              'list_account_agreements',
              'list_child_accounts',
              'view_user',
              'list_users',
              'update_account',
              'update_account_settings',
              'enable_managed',
              'create_service_transfer',
              'list_maintenances',
              'create_oauth_client',
              'acknowledge_account_agreement',
              'enroll_beta_program',
              'list_enrolled_beta_programs',
              'create_user',
              'update_user',
              'delete_user',
              'create_linode',
              'list_linodes',
              'allocate_ip',
              'assign_ips',
              'share_ips',
              'assign_ipv4',
              'share_ipv4',
              'create_ipv6_range',
              'view_linode',
              'view_linode_stats',
              'view_linode_monthly_stats',
              'view_linode_network_transfer',
              'view_linode_monthly_network_transfer_stats',
              'list_linode_types',
              'list_linode_volumes',
              'list_linode_backups',
              'list_linode_config_profiles',
              'list_linode_disks',
              'list_linode_firewalls',
              'view_linode_networking_info',
              'list_linode_nodebalancers',
              'list_linode_kernels',
              'view_linode_type',
              'view_linode_backup',
              'view_linode_config_profile',
              'list_linode_config_profile_interfaces',
              'view_linode_config_profile_interface',
              'view_linode_disk',
              'view_linode_ip_address',
              'view_linode_kernel',
              'boot_linode',
              'clone_linode',
              'migrate_linode',
              'upgrade_linode',
              'password_reset_linode',
              'reboot_linode',
              'rebuild_linode',
              'rescue_linode',
              'resize_linode',
              'shutdown_linode',
              'create_linode_backup_snapshot',
              'enable_linode_backups',
              'create_linode_config_profile',
              'create_linode_disk',
              'allocate_linode_ip_address',
              'restore_linode_backup',
              'update_linode_config_profile',
              'create_linode_config_profile_interface',
              'reorder_linode_config_profile_interfaces',
              'update_linode_config_profile_interface',
              'update_linode_disk',
              'clone_linode_disk',
              'reset_linode_disk_root_password',
              'resize_linode_disk',
              'update_linode_ip_address',
              'delete_linode',
              'cancel_linode_backups',
              'delete_linode_config_profile',
              'delete_linode_config_profile_interface',
              'delete_linode_disk',
              'delete_linode_ip_address',
              'create_firewall',
              'list_firewalls',
              'delete_firewall',
              'create_firewall_device',
              'delete_firewall_device',
              'update_firewall',
              'update_firewall_rules',
              'view_firewall',
              'view_firewall_device',
              'list_firewall_devices',
              'create_image',
              'upload_image',
              'list_images',
              'view_image',
              'update_image',
              'delete_image',
              'create_vpc',
              'list_vpcs',
              'list_all_vpc_ipaddresses',
              'view_vpc',
              'list_vpc_ip_addresses',
              'list_vpc_subnets',
              'view_vpc_subnet',
              'update_vpc',
              'update_vpc_subnet',
              'delete_vpc',
              'create_vpc_subnet',
              'delete_vpc_subnet',
              'create_volume',
              'list_volumes',
              'view_volume',
              'update_volume',
              'attach_volume',
              'clone_volume',
              'detach_volume',
              'resize_volume',
              'delete_volume',
              'create_nodebalancer',
              'list_nodebalancers',
              'view_nodebalancer',
              'list_nodebalancer_firewalls',
              'view_nodebalancer_statistics',
              'list_nodebalancer_configs',
              'view_nodebalancer_config',
              'list_nodebalancer_config_nodes',
              'view_nodebalancer_config_node',
              'update_nodebalancer',
              'add_nodebalancer_config',
              'update_nodebalancer_config',
              'rebuild_nodebalancer_config',
              'add_nodebalancer_config_node',
              'update_nodebalancer_config_node',
              'delete_nodebalancer',
              'delete_nodebalancer_config',
              'delete_nodebalancer_config_node',
            ],
          },
          {
            description:
              'Access to perform any supported action on all linode instances in the account',
            name: 'account_retail_owner',
            permissions: ['cancel_account'],
          },
          {
            description: 'Access to view bills, payments in the account',
            name: 'billing_viewer',
            permissions: [
              'list_payments',
              'list_invoices',
              'list_payment_methods',
              'view_invoice',
              'list_invoice_items',
              'view_payment_method',
              'view_payment',
            ],
          },
          {
            description:
              'Access to view bills, and make payments in the account',
            name: 'billing_admin',
            permissions: [
              'list_payments',
              'list_invoices',
              'list_payment_methods',
              'view_invoice',
              'list_invoice_items',
              'view_payment_method',
              'view_payment',
              'make_payment',
              'create_payment_method',
              'create_promo_code',
              'delete_payment_method',
              'set_default_payment_method',
            ],
          },
        ],
      },
      {
        resource_type: 'linode',
        roles: [
          {
            description: 'Access to create a linode instance',
            name: 'linode_creator',
            permissions: [
              'create_linode',
              'list_linodes',
              'allocate_ip',
              'assign_ips',
              'share_ips',
              'assign_ipv4',
              'share_ipv4',
              'create_ipv6_range',
            ],
          },
          {
            description: 'Access to administer all linode instances',
            name: 'account_linode_admin',
            permissions: [
              'create_linode',
              'list_linodes',
              'allocate_ip',
              'assign_ips',
              'share_ips',
              'assign_ipv4',
              'share_ipv4',
              'create_ipv6_range',
              'view_linode',
              'view_linode_stats',
              'view_linode_monthly_stats',
              'view_linode_network_transfer',
              'view_linode_monthly_network_transfer_stats',
              'list_linode_types',
              'list_linode_volumes',
              'list_linode_backups',
              'list_linode_disks',
              'list_linode_firewalls',
              'view_linode_networking_info',
              'list_linode_nodebalancers',
              'list_linode_kernels',
              'view_linode_type',
              'view_linode_backup',
              'view_linode_config_profile',
              'list_linode_config_profile_interfaces',
              'view_linode_config_profile_interface',
              'view_linode_disk',
              'view_linode_ip_address',
              'view_linode_kernel',
              'boot_linode',
              'clone_linode',
              'migrate_linode',
              'upgrade_linode',
              'password_reset_linode',
              'reboot_linode',
              'rebuild_linode',
              'rescue_linode',
              'resize_linode',
              'shutdown_linode',
              'create_linode_backup_snapshot',
              'enable_linode_backups',
              'create_linode_config_profile',
              'list_linode_config_profiles',
              'create_linode_disk',
              'allocate_linode_ip_address',
              'restore_linode_backup',
              'update_linode_config_profile',
              'create_linode_config_profile_interface',
              'reorder_linode_config_profile_interfaces',
              'update_linode_config_profile_interface',
              'update_linode_disk',
              'clone_linode_disk',
              'reset_linode_disk_root_password',
              'resize_linode_disk',
              'update_linode_ip_address',
              'delete_linode',
              'cancel_linode_backups',
              'delete_linode_config_profile',
              'delete_linode_config_profile_interface',
              'delete_linode_disk',
              'delete_linode_ip_address',
            ],
          },
        ],
      },
      {
        resource_type: 'firewall',
        roles: [
          {
            description: 'Access to create a firewall instance',
            name: 'firewall_creator',
            permissions: ['create_firewall', 'list_firewalls'],
          },
          {
            description: 'Access to administer all firewall instances',
            name: 'account_firewall_admin',
            permissions: [
              'create_firewall',
              'list_firewalls',
              'delete_firewall',
              'create_firewall_device',
              'delete_firewall_device',
              'update_firewall',
              'update_firewall_rules',
              'view_firewall',
              'view_firewall_device',
              'list_firewall_devices',
            ],
          },
        ],
      },
      {
        resource_type: 'image',
        roles: [
          {
            description: 'Access to create a image instance',
            name: 'image_creator',
            permissions: ['create_image', 'upload_image', 'list_images'],
          },
          {
            description: 'Access to administer all image instances',
            name: 'account_image_admin',
            permissions: [
              'create_image',
              'upload_image',
              'list_images',
              'view_image',
              'update_image',
              'delete_image',
            ],
          },
        ],
      },
      {
        resource_type: 'vpc',
        roles: [
          {
            description: 'Access to create a vpc instance',
            name: 'vpc_creator',
            permissions: [
              'create_vpc',
              'list_vpcs',
              'list_all_vpc_ipaddresses',
            ],
          },
          {
            description: 'Access to administer all vpc instances',
            name: 'account_vpc_admin',
            permissions: [
              'create_vpc',
              'list_vpcs',
              'list_all_vpc_ipaddresses',
              'view_vpc',
              'list_vpc_ip_addresses',
              'list_vpc_subnets',
              'view_vpc_subnet',
              'update_vpc',
              'update_vpc_subnet',
              'delete_vpc',
              'create_vpc_subnet',
              'delete_vpc_subnet',
            ],
          },
        ],
      },
      {
        resource_type: 'volume',
        roles: [
          {
            description: 'Access to create a volume instance',
            name: 'volume_creator',
            permissions: ['create_volume', 'list_volumes'],
          },
          {
            description: 'Access to administer all volume instances',
            name: 'account_volume_admin',
            permissions: [
              'create_volume',
              'list_volumes',
              'view_volume',
              'update_volume',
              'attach_volume',
              'clone_volume',
              'detach_volume',
              'resize_volume',
              'delete_volume',
            ],
          },
        ],
      },
      {
        resource_type: 'nodebalancer',
        roles: [
          {
            description: 'Access to create a nodebalancer instance',
            name: 'nodebalancer_creator',
            permissions: ['create_nodebalancer', 'list_nodebalancers'],
          },
          {
            description: 'Access to administer all nodebalancer instances',
            name: 'account_nodebalancer_admin',
            permissions: [
              'create_nodebalancer',
              'list_nodebalancers',
              'view_nodebalancer',
              'list_nodebalancer_firewalls',
              'view_nodebalancer_statistics',
              'list_nodebalancer_configs',
              'view_nodebalancer_config',
              'list_nodebalancer_config_nodes',
              'view_nodebalancer_config_node',
              'update_nodebalancer',
              'add_nodebalancer_config',
              'update_nodebalancer_config',
              'rebuild_nodebalancer_config',
              'add_nodebalancer_config_node',
              'update_nodebalancer_config_node',
              'delete_nodebalancer',
              'delete_nodebalancer_config',
              'delete_nodebalancer_config_node',
            ],
          },
        ],
      },
    ],
    resource_access: [
      {
        resource_type: 'linode',
        roles: [
          {
            description: 'Access to administer a linode instance',
            name: 'linode_admin',
            permissions: [
              'create_linode',
              'list_linodes',
              'allocate_ip',
              'assign_ips',
              'share_ips',
              'assign_ipv4',
              'share_ipv4',
              'create_ipv6_range',
              'view_linode',
              'view_linode_stats',
              'view_linode_monthly_stats',
              'view_linode_network_transfer',
              'view_linode_monthly_network_transfer_stats',
              'list_linode_types',
              'list_linode_volumes',
              'list_linode_backups',
              'list_linode_config_profiles',
              'list_linode_disks',
              'list_linode_firewalls',
              'view_linode_networking_info',
              'list_linode_nodebalancers',
              'list_linode_kernels',
              'view_linode_type',
              'view_linode_backup',
              'view_linode_config_profile',
              'list_linode_config_profile_interfaces',
              'view_linode_config_profile_interface',
              'view_linode_disk',
              'view_linode_ip_address',
              'view_linode_kernel',
              'boot_linode',
              'clone_linode',
              'migrate_linode',
              'upgrade_linode',
              'password_reset_linode',
              'reboot_linode',
              'rebuild_linode',
              'rescue_linode',
              'resize_linode',
              'shutdown_linode',
              'create_linode_backup_snapshot',
              'enable_linode_backups',
              'create_linode_config_profile',
              'create_linode_disk',
              'allocate_linode_ip_address',
              'restore_linode_backup',
              'update_linode_config_profile',
              'create_linode_config_profile_interface',
              'reorder_linode_config_profile_interfaces',
              'update_linode_config_profile_interface',
              'update_linode_disk',
              'clone_linode_disk',
              'reset_linode_disk_root_password',
              'resize_linode_disk',
              'update_linode_ip_address',
              'delete_linode',
              'cancel_linode_backups',
              'delete_linode_config_profile',
              'delete_linode_config_profile_interface',
              'delete_linode_disk',
              'delete_linode_ip_address',
            ],
          },
          {
            description: 'Access to view a linode instance',
            name: 'linode_viewer',
            permissions: [
              'view_linode',
              'view_linode_stats',
              'view_linode_monthly_stats',
              'view_linode_network_transfer',
              'view_linode_monthly_network_transfer_stats',
              'list_linode_types',
              'list_linode_volumes',
              'list_linode_backups',
              'list_linode_config_profiles',
              'list_linode_disks',
              'list_linode_firewalls',
              'view_linode_networking_info',
              'list_linode_nodebalancers',
              'list_linode_kernels',
              'view_linode_type',
              'view_linode_backup',
              'view_linode_config_profile',
              'list_linode_config_profile_interfaces',
              'view_linode_config_profile_interface',
              'view_linode_disk',
              'view_linode_ip_address',
              'view_linode_kernel',
            ],
          },
          {
            description: 'Access to view a linode instance',
            name: 'linode_contributor',
            permissions: [
              'view_linode',
              'view_linode_stats',
              'view_linode_monthly_stats',
              'view_linode_network_transfer',
              'view_linode_monthly_network_transfer_stats',
              'list_linode_types',
              'list_linode_volumes',
              'list_linode_backups',
              'list_linode_config_profiles',
              'list_linode_disks',
              'list_linode_firewalls',
              'view_linode_networking_info',
              'list_linode_nodebalancers',
              'list_linode_kernels',
              'view_linode_type',
              'view_linode_backup',
              'view_linode_config_profile',
              'list_linode_config_profile_interfaces',
              'view_linode_config_profile_interface',
              'view_linode_disk',
              'view_linode_ip_address',
              'view_linode_kernel',
              'boot_linode',
              'clone_linode',
              'migrate_linode',
              'upgrade_linode',
              'password_reset_linode',
              'reboot_linode',
              'rebuild_linode',
              'rescue_linode',
              'resize_linode',
              'shutdown_linode',
              'create_linode_backup_snapshot',
              'cancel_linode_backups',
              'enable_linode_backups',
              'create_linode_config_profile',
              'create_linode_disk',
              'allocate_linode_ip_address',
              'restore_linode_backup',
              'update_linode_config_profile',
              'create_linode_config_profile_interface',
              'reorder_linode_config_profile_interfaces',
              'update_linode_config_profile_interface',
              'update_linode_disk',
              'clone_linode_disk',
              'reset_linode_disk_root_password',
              'resize_linode_disk',
              'update_linode_ip_address',
            ],
          },
        ],
      },
      {
        resource_type: 'image',
        roles: [
          {
            description: 'Access to administer a image instance',
            name: 'image_admin',
            permissions: [
              'create_image',
              'upload_image',
              'list_images',
              'view_image',
              'update_image',
              'delete_image',
            ],
          },
          {
            description: 'Access to view an image instance',
            name: 'image_viewer',
            permissions: ['view_image'],
          },
          {
            description: 'Access to update an image instance',
            name: 'image_contributor',
            permissions: ['view_image', 'update_image'],
          },
        ],
      },
      {
        resource_type: 'vpc',
        roles: [
          {
            description: 'Access to administer a vpc instance',
            name: 'vpc_admin',
            permissions: [
              'create_vpc',
              'list_vpcs',
              'list_all_vpc_ipaddresses',
              'view_vpc',
              'list_vpc_ip_addresses',
              'list_vpc_subnets',
              'view_vpc_subnet',
              'update_vpc',
              'update_vpc_subnet',
              'delete_vpc',
              'create_vpc_subnet',
              'delete_vpc_subnet',
            ],
          },
          {
            description: 'Access to view a vpc instance',
            name: 'vpc_viewer',
            permissions: [
              'view_vpc',
              'list_vpc_ip_addresses',
              'list_vpc_subnets',
              'view_vpc_subnet',
            ],
          },
          {
            description: 'Access to update a vpc instance',
            name: 'vpc_contributor',
            permissions: [
              'view_vpc',
              'list_vpc_ip_addresses',
              'list_vpc_subnets',
              'view_vpc_subnet',
              'update_vpc',
              'update_vpc_subnet',
              'delete_vpc',
              'create_vpc_subnet',
              'delete_vpc_subnet',
            ],
          },
        ],
      },
      {
        resource_type: 'volume',
        roles: [
          {
            description: 'Access to administer a volume instance',
            name: 'volume_admin',
            permissions: [
              'view_volume',
              'update_volume',
              'attach_volume',
              'clone_volume',
              'detach_volume',
              'resize_volume',
              'delete_volume',
            ],
          },
          {
            description: 'Access to view a volume instance',
            name: 'volume_viewer',
            permissions: ['view_volume'],
          },
          {
            description: 'Access to update a volume instance',
            name: 'volume_contributor',
            permissions: [
              'view_volume',
              'update_volume',
              'attach_volume',
              'clone_volume',
              'detach_volume',
              'resize_volume',
            ],
          },
        ],
      },
      {
        resource_type: 'nodebalancer',
        roles: [
          {
            description: 'Access to administer a nodebalancer instance',
            name: 'nodebalancer_admin',
            permissions: [
              'view_nodebalancer',
              'list_nodebalancer_firewalls',
              'view_nodebalancer_statistics',
              'list_nodebalancer_configs',
              'view_nodebalancer_config',
              'list_nodebalancer_config_nodes',
              'view_nodebalancer_config_node',
              'update_nodebalancer',
              'add_nodebalancer_config',
              'update_nodebalancer_config',
              'rebuild_nodebalancer_config',
              'add_nodebalancer_config_node',
              'update_nodebalancer_config_node',
              'delete_nodebalancer',
              'delete_nodebalancer_config',
              'delete_nodebalancer_config_node',
            ],
          },
          {
            description: 'Access to view a nodebalancer instance',
            name: 'nodebalancer_viewer',
            permissions: [
              'view_nodebalancer',
              'list_nodebalancer_firewalls',
              'view_nodebalancer_statistics',
              'list_nodebalancer_configs',
              'view_nodebalancer_config',
              'list_nodebalancer_config_nodes',
              'view_nodebalancer_config_node',
            ],
          },
          {
            description: 'Access to update a nodebalancer instance',
            name: 'nodebalancer_contributor',
            permissions: [
              'view_nodebalancer',
              'list_nodebalancer_firewalls',
              'view_nodebalancer_statistics',
              'list_nodebalancer_configs',
              'view_nodebalancer_config',
              'list_nodebalancer_config_nodes',
              'view_nodebalancer_config_node',
              'update_nodebalancer',
              'add_nodebalancer_config',
              'update_nodebalancer_config',
              'rebuild_nodebalancer_config',
              'add_nodebalancer_config_node',
              'update_nodebalancer_config_node',
            ],
          },
        ],
      },
    ],
  }
);
