import { styled } from '@mui/material/styles';

/**
 * Styled container for rendering HTML content from the API
 * This provides consistent styling for all HTML elements across tabs
 * Styles follow Figma design specifications
 */
export const StyledTabContent = styled('div')(({ theme }) => ({
  '& a': {
    color: theme.palette.primary.main,
    textDecoration: 'none',
    '&:hover': {
      textDecoration: 'underline',
    },
  },
  '& blockquote': {
    borderLeft: `4px solid ${theme.borderColors.borderTable}`,
    fontStyle: 'italic',
    margin: '16px 0',
    paddingLeft: theme.spacingFunction(16),
  },
  '& code': {
    backgroundColor: theme.bg.offWhite,
    borderRadius: '3px',
    fontFamily: '"Courier New", Courier, monospace',
    fontSize: theme.tokens.font.FontSize.Xs,
    padding: '2px 6px',
  },
  '& h1': {
    color: theme.tokens.alias.Content.Text.Primary.Default,
    fontFamily: theme.font.bold,
    fontSize: theme.tokens.font.FontSize.L,
    fontStyle: 'normal',
    lineHeight: theme.tokens.font.LineHeight.M,
    margin: 0,
    paddingBottom: theme.tokens.spacing.S16,
  },
  '& h2': {
    color: theme.tokens.alias.Content.Text.Primary.Default,
    fontFamily: theme.font.bold,
    fontSize: theme.tokens.font.FontSize.M,
    fontStyle: 'normal',
    lineHeight: theme.tokens.font.LineHeight.S,
    margin: 0,
    paddingBottom: theme.tokens.spacing.S16,
  },
  '& h3': {
    color: theme.tokens.alias.Content.Text.Primary.Default,
    fontFamily: theme.font.bold,
    fontSize: theme.tokens.font.FontSize.S,
    fontStyle: 'normal',
    lineHeight: theme.tokens.font.LineHeight.Xs,
    margin: 0,
    paddingBottom: theme.tokens.spacing.S16,
  },
  '& h4, & h5, & h6': {
    color: theme.tokens.alias.Content.Text.Primary.Default,
    fontFamily: theme.font.bold,
    fontSize: theme.tokens.font.FontSize.Xs,
    fontStyle: 'normal',
    lineHeight: theme.tokens.font.LineHeight.Xs,
    margin: 0,
    paddingBottom: theme.tokens.spacing.S16,
  },
  '& img': {
    display: 'block',
    height: 'auto',
    margin: '16px 0',
    maxWidth: '100%',
  },
  '& li': {
    color: theme.tokens.alias.Content.Text.Primary.Default,
    fontFamily: theme.font.normal,
    fontSize: theme.tokens.font.FontSize.Xs,
    fontStyle: 'normal',
    lineHeight: theme.tokens.font.LineHeight.Xs,
  },
  '& ol': {
    listStyleType: 'decimal',
    margin: 0,
    paddingBottom: theme.tokens.spacing.S16,
    paddingLeft: theme.spacingFunction(32),
  },
  '& p': {
    color: theme.tokens.alias.Content.Text.Primary.Default,
    fontFamily: theme.font.normal,
    fontSize: theme.tokens.font.FontSize.Xs,
    fontStyle: 'normal',
    lineHeight: theme.tokens.font.LineHeight.Xs,
    margin: 0,
    paddingBottom: theme.tokens.spacing.S16,
  },
  '& pre': {
    backgroundColor: theme.bg.offWhite,
    borderRadius: '4px',
    fontFamily: '"Courier New", Courier, monospace',
    fontSize: theme.tokens.font.FontSize.Xs,
    margin: '16px 0',
    overflowX: 'auto',
    padding: theme.spacingFunction(16),
  },
  '& strong': {
    fontFamily: theme.font.bold,
  },
  '& table': {
    borderCollapse: 'collapse',
    marginBottom: theme.tokens.spacing.S16,
    marginTop: 0,
    width: '100%',
  },
  '& td': {
    alignItems: 'center',
    alignSelf: 'stretch',
    borderBottom: `1px solid ${theme.tokens.component.Table.Row.Border}`,
    color: theme.tokens.alias.Content.Text.Primary.Default,
    display: 'table-cell',
    fontFamily: theme.font.normal,
    fontSize: theme.tokens.font.FontSize.Xs,
    fontStyle: 'normal',
    gap: '8px',
    height: '40px',
    lineHeight: theme.tokens.font.LineHeight.Xs,
    padding: '10px 12px',
    verticalAlign: 'middle',
  },
  '& th': {
    alignItems: 'center',
    background: theme.tokens.component.Table.HeaderNested.Background,
    borderBottom: `1px solid ${theme.tokens.component.Table.Row.Border}`,
    display: 'table-cell',
    flex: '1 0 0',
    fontFamily: theme.font.bold,
    fontSize: theme.tokens.font.FontSize.Xs,
    gap: '8px',
    lineHeight: theme.tokens.font.LineHeight.Xs,
    padding: '12px 16px 12px 12px',
    textAlign: 'left',
    verticalAlign: 'middle',
  },
  '& ul': {
    listStyleType: 'disc',
    margin: 0,
    paddingBottom: theme.tokens.spacing.S16,
    paddingLeft: theme.spacingFunction(32),
  },
  color: theme.tokens.alias.Content.Text.Primary.Default,
  fontFamily: theme.font.normal,
  fontSize: theme.tokens.font.FontSize.Xs,
  lineHeight: theme.tokens.font.LineHeight.Xs,
  wordBreak: 'break-word',
}));
