export const distroIcons = {
  AlmaLinux: 'almalinux',
  Alpine: 'alpine',
  Arch: 'archlinux',
  CentOS: 'centos',
  CoreOS: 'coreos',
  Debian: 'debian',
  Fedora: 'fedora',
  Gentoo: 'gentoo',
  Kali: 'kali-linux',
  openSUSE: 'opensuse',
  Rocky: 'rocky-linux',
  Slackware: 'slackware',
  Ubuntu: 'ubuntu',
};
