export const deviceSlots = [
  'sda',
  'sdb',
  'sdc',
  'sdd',
  'sde',
  'sdf',
  'sdg',
  'sdh',
  'sdi',
  'sdj',
  'sdk',
  'sdl',
  'sdm',
  'sdn',
  'sdo',
  'sdp',
  'sdq',
  'sdr',
  'sds',
  'sdt',
  'sdu',
  'sdv',
  'sdw',
  'sdx',
  'sdy',
  'sdz',
  'sdaa',
  'sdab',
  'sdac',
  'sdad',
  'sdae',
  'sdaf',
  'sdag',
  'sdah',
  'sdai',
  'sdaj',
  'sdak',
  'sdal',
  'sdam',
  'sdan',
  'sdao',
  'sdap',
  'sdaq',
  'sdar',
  'sdas',
  'sdat',
  'sdau',
  'sdav',
  'sdaw',
  'sdax',
  'sday',
  'sdaz',
  'sdba',
  'sdbb',
  'sdbc',
  'sdbd',
  'sdbe',
  'sdbf',
  'sdbg',
  'sdbh',
  'sdbi',
  'sdbj',
  'sdbk',
  'sdbl',
];

export const pathsOptions = [
  { label: '/dev/sda', value: '/dev/sda' },
  { label: '/dev/sdb', value: '/dev/sdb' },
  { label: '/dev/sdc', value: '/dev/sdc' },
  { label: '/dev/sdd', value: '/dev/sdd' },
  { label: '/dev/sde', value: '/dev/sde' },
  { label: '/dev/sdf', value: '/dev/sdf' },
  { label: '/dev/sdg', value: '/dev/sdg' },
  { label: '/dev/sdh', value: '/dev/sdh' },
  { label: '/dev/sdi', value: '/dev/sdi' },
  { label: '/dev/sdj', value: '/dev/sdj' },
  { label: '/dev/sdk', value: '/dev/sdk' },
  { label: '/dev/sdl', value: '/dev/sdl' },
  { label: '/dev/sdm', value: '/dev/sdm' },
  { label: '/dev/sdn', value: '/dev/sdn' },
  { label: '/dev/sdo', value: '/dev/sdo' },
  { label: '/dev/sdp', value: '/dev/sdp' },
  { label: '/dev/sdq', value: '/dev/sdq' },
  { label: '/dev/sdr', value: '/dev/sdr' },
  { label: '/dev/sds', value: '/dev/sds' },
  { label: '/dev/sdt', value: '/dev/sdt' },
  { label: '/dev/sdu', value: '/dev/sdu' },
  { label: '/dev/sdv', value: '/dev/sdv' },
  { label: '/dev/sdw', value: '/dev/sdw' },
  { label: '/dev/sdx', value: '/dev/sdx' },
  { label: '/dev/sdy', value: '/dev/sdy' },
  { label: '/dev/sdz', value: '/dev/sdz' },
  { label: '/dev/sdaa', value: '/dev/sdaa' },
  { label: '/dev/sdab', value: '/dev/sdab' },
  { label: '/dev/sdac', value: '/dev/sdac' },
  { label: '/dev/sdad', value: '/dev/sdad' },
  { label: '/dev/sdae', value: '/dev/sdae' },
  { label: '/dev/sdaf', value: '/dev/sdaf' },
  { label: '/dev/sdag', value: '/dev/sdag' },
  { label: '/dev/sdah', value: '/dev/sdah' },
  { label: '/dev/sdai', value: '/dev/sdai' },
  { label: '/dev/sdaj', value: '/dev/sdaj' },
  { label: '/dev/sdak', value: '/dev/sdak' },
  { label: '/dev/sdal', value: '/dev/sdal' },
  { label: '/dev/sdam', value: '/dev/sdam' },
  { label: '/dev/sdan', value: '/dev/sdan' },
  { label: '/dev/sdao', value: '/dev/sdao' },
  { label: '/dev/sdap', value: '/dev/sdap' },
  { label: '/dev/sdaq', value: '/dev/sdaq' },
  { label: '/dev/sdar', value: '/dev/sdar' },
  { label: '/dev/sdas', value: '/dev/sdas' },
  { label: '/dev/sdat', value: '/dev/sdat' },
  { label: '/dev/sdau', value: '/dev/sdau' },
  { label: '/dev/sdav', value: '/dev/sdav' },
  { label: '/dev/sdaw', value: '/dev/sdaw' },
  { label: '/dev/sdax', value: '/dev/sdax' },
  { label: '/dev/sday', value: '/dev/sday' },
  { label: '/dev/sdaz', value: '/dev/sdaz' },
  { label: '/dev/sdba', value: '/dev/sdba' },
  { label: '/dev/sdbb', value: '/dev/sdbb' },
  { label: '/dev/sdbc', value: '/dev/sdbc' },
  { label: '/dev/sdbd', value: '/dev/sdbd' },
  { label: '/dev/sdbe', value: '/dev/sdbe' },
  { label: '/dev/sdbf', value: '/dev/sdbf' },
  { label: '/dev/sdbg', value: '/dev/sdbg' },
  { label: '/dev/sdbh', value: '/dev/sdbh' },
  { label: '/dev/sdbi', value: '/dev/sdbi' },
  { label: '/dev/sdbj', value: '/dev/sdbj' },
  { label: '/dev/sdbk', value: '/dev/sdbk' },
  { label: '/dev/sdbl', value: '/dev/sdbl' },
];

export const pathsOptionsLabels = pathsOptions.map((path) => path.label);
