name: Run Tests On Push/Schedule
concurrency: UI_TESTS
env:
  USER_1: ${{ secrets.USER_1 }}
  USER_2: ${{ secrets.USER_2 }}
  USER_3: ${{ secrets.USER_3 }}
  USER_4: ${{ secrets.USER_4 }}
  CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
  CY_TEST_FAIL_ON_MANAGED: 1
  CY_TEST_RESET_PREFERENCES: 1
  CY_TEST_SPLIT_RUN: 1
  CY_TEST_SPLIT_RUN_TOTAL: 4
on:
  schedule:
    - cron: "0 13 * * 1-5"
  push:
    branches:
      - develop
      - staging
      - master

jobs:
  run-cypress-e2e:
    name: Cypress Tests (User ${{ matrix.user.index }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        user:
          - { index: 1, name: 'USER_1' }
          - { index: 2, name: 'USER_2' }
          - { index: 3, name: 'USER_3' }
          - { index: 4, name: 'USER_4' }
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: "20.17"
      - run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - run: |
          echo "REACT_APP_LAUNCH_DARKLY_ID=${{ secrets.REACT_APP_LAUNCH_DARKLY_ID }}" >> ./packages/manager/.env
          echo "REACT_APP_CLIENT_ID=$CLIENT_ID" >> ./packages/manager/.env
          echo "REACT_APP_LOGIN_ROOT=${{ secrets.REACT_APP_LOGIN_ROOT }}" >> ./packages/manager/.env
          echo "REACT_APP_API_ROOT=${{ secrets.REACT_APP_API_ROOT }}" >> ./packages/manager/.env
          echo "REACT_APP_APP_ROOT=${{ secrets.REACT_APP_APP_ROOT }}" >> ./packages/manager/.env
          echo "REACT_APP_DISABLE_NEW_RELIC=1" >> ./packages/manager/.env
          echo "MANAGER_OAUTH=${{ secrets[matrix.user.name] }}" >> ./packages/manager/.env
          echo "CY_TEST_SPLIT_RUN_INDEX=${{ matrix.user.index }}" >> ./packages/manager/.env
      - run: pnpm install --frozen-lockfile
      - run: pnpm run --filter @linode/validation build
      - run: pnpm run --filter @linode/api-v4 build
      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: packages/manager
          wait-on: "http://localhost:3000"
          wait-on-timeout: 1000
          install: false
          build: pnpm run build
          start: pnpm start:ci
          browser: chrome
          record: false
          parallel: false
