name: ESLint Review
on: [pull_request]
jobs:
  eslint:
    name: ESLint Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    strategy:
      matrix:
        package: [manager, api-v4, queries, shared, ui, utilities, validation]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          run_install: false
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: "20.17"
          cache: "pnpm"
      - run: pnpm install
      - uses: abailly-akamai/action-eslint@master
        with:
          workdir: packages/${{ matrix.package }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: warning  # This will report both warnings and errors
          filter_mode: added  # Only comment on new/modified lines