name: ESLint Review
on: [pull_request]
jobs:
  eslint:
    name: ESLint Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    strategy:
      matrix:
        package: [manager, api-v4, queries, shared, ui, utilities, validation]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2.4.1
        with:
          run_install: false
          version: 10
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - run: pnpm install
      - uses: abailly-akamai/action-eslint@8ad68ba04fa60924ef7607b07deb5989f38f5ed6 # v1.0.2
        with:
          workdir: packages/${{ matrix.package }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: warning # This will report both warnings and errors
          filter_mode: added # Only comment on new/modified lines
