# This workflow run unit tests for the SDK as well as a build. It will then
# run npm publish if the preceding steps succeeded.

name: Linode JS SDK

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn install:all
    - name: Unit tests
      run: yarn workspace @linode/api-v4 run test
    - name: Build SDK
      run: yarn workspace @linode/api-v4 build
    - name: Archive production build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lib
        path: packages/@linode/api-v4/lib
    # - name: Publish
    #   run: yarn workspace @linode/api-v4 publish --dry-run
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}